server:
  port: 8084
spring:
  application:
    name: demand-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  cloud:
    config:
      name: demand_service
