server:
  port: 5555
spring:
  application:
    name: gateway-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  cloud:
    config:
      name: gateway_service