server:
  port: 8085
spring:
  application:
    name: client-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  cloud:
    config:
      name: client_service
