server:
  port: 8083
spring:
  application:
    name: notification-service
  config:
    import : optional:configserver:http://localhost:9999
  cloud:
    config:
      name: notification_service
      label: main