server:
  port: 8083
spring:
  application:
    name: notification-service
  config:
    import : optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  cloud:
    config:
      name: notification_service
