server:
  port: 8081
spring:
  application:
    name: packs-service
  config:
    import: optional:configserver:${CONFIG_SERVICE_URL:http://localhost:9999}
  cloud:
    config:
      name: packs_service
#      label: main